branch-defaults:
  driver-socket:
    environment: transit-driver-prod
    group_suffix: null
environment-defaults:
  transit-driver-prod:
    branch: null
    repository: null
global:
  application_name: transit_driver
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: 6.7.2
  profile: null
  repository: null
  sc: git
  workspace_type: Application
